name: safehand_poultry_manager
description: "A poultry management app."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Local Database
  hive_ce: ^2.15.1
  hive_ce_flutter: ^2.0.1
  path_provider: ^2.1.5

  # Navigation
  go_router: ^14.0.0

  # Charts
  fl_chart: ^1.1.1
  uuid: ^4.5.2
  rxdart: ^0.28.0
  intl: ^0.20.2
  pdf: ^3.11.3
  printing: ^5.14.2

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  
  # Code Generation
  riverpod_generator: ^2.6.1
  build_runner: ^2.4.13
  hive_ce_generator: ^1.6.0
  
  # Linting
  flutter_lints: ^5.0.0
  riverpod_lint: ^2.6.2

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_sm.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo_sm.png"
    background_color: "#4CAF50"
    theme_color: "#4CAF50"
  windows:
    generate: true
    image_path: "assets/images/logo_sm.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/images/logo_sm.png"

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/logo_bg.png
    - assets/images/logo_sm.png
